
id: hl7.org.nz.fhir.ig.medtech
canonical: http://hl7.org.nz/fhir/ig/medtech
version: 0.1.0
name: medtechIG
title: medTech IG
status: active
publisher:
  name: David Hay
  email: mailto:david.hay25@gmail.com
description: The HPI facade
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
copyrightYear: 2021+
releaseLabel: CI Build

# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To use a provided ig-data/ig.ini file, delete the "template" property below.                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# template: fhir.base.template#current


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  API: capabilityStatement.html
  Example queries: exampleQueries.html
  Extensions: extensions.html
  Profiles: profiles.html
  Artifact Index: artifacts.html
  General Notes: general.html
 

  Support:
    "FHIR Spec ": "{{site.data.fhir.path}}index.html"
